[package]
authors = ["Sebastian Kliś <saklis@outlook.com>"]
edition = "2018"
name = "bevy-editor-viewport"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.2.1"